/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Analizador.AnalizadorLexico;
import graficos.GeneradorAFD;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelos.ErrorLexico;
import modelos.Reportes;
import modelos.Token;

/**
 *
 * @author fernan
 */
public class Vista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista.class.getName());

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEditor = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnAbrir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnAnalizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTokens = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaErrores = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        ReporteDeTokens = new javax.swing.JMenuItem();
        ReporteDeErrores = new javax.swing.JMenuItem();
        ReporteDeEstadisticas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        GeneradorDeAFD = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PromptZal - Analizador Lexico");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEditor.setColumns(20);
        txtEditor.setRows(5);
        jScrollPane1.setViewportView(txtEditor);

        jLabel1.setText("Codigo PromptZal");

        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAnalizar.setText("Analizar");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        tablaTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Lexema", "Tipo", "Linea", "Columna"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaTokens);

        tablaErrores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Lexema", "Tipo de Error", "Fila", "Columna"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaErrores);

        jLabel2.setText("Tokens");

        jLabel3.setText("Errores");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnAbrir)
                        .addGap(159, 159, 159)
                        .addComponent(btnGuardar)
                        .addGap(112, 112, 112)
                        .addComponent(btnAnalizar))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel2)))
                                .addGap(182, 182, 182)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(567, 567, 567))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrir)
                    .addComponent(btnGuardar)
                    .addComponent(btnAnalizar))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 1000));

        jMenu3.setText("Archivo");

        jMenuItem1.setText("Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Abrir");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Guardar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Salir");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Analizar");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reportes");

        ReporteDeTokens.setText("Reporte de Tokens");
        ReporteDeTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteDeTokensActionPerformed(evt);
            }
        });
        jMenu5.add(ReporteDeTokens);

        ReporteDeErrores.setText("Reporte de Errores");
        ReporteDeErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteDeErroresActionPerformed(evt);
            }
        });
        jMenu5.add(ReporteDeErrores);

        ReporteDeEstadisticas.setText("Estadisticas");
        ReporteDeEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteDeEstadisticasActionPerformed(evt);
            }
        });
        jMenu5.add(ReporteDeEstadisticas);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Automata");

        GeneradorDeAFD.setText("Generar AFD");
        GeneradorDeAFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneradorDeAFDActionPerformed(evt);
            }
        });
        jMenu6.add(GeneradorDeAFD);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        // TODO add your handling code here:
        
        JFileChooser selector = new JFileChooser();
        selector.setDialogTitle("Abrir archivo PromptZal");

        // Mostrar solamente archivos .pz
        FileNameExtensionFilter filtro =
                new FileNameExtensionFilter(
                        "Archivos PromptZal (*.pz)",
                        "pz"
                );

        selector.setFileFilter(filtro);

        int resultado = selector.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {

            File archivo = selector.getSelectedFile();

            try {

                BufferedReader lector =
                        new BufferedReader(new FileReader(archivo));

                StringBuilder contenido = new StringBuilder();

                String linea;

                while ((linea = lector.readLine()) != null) {
                    contenido.append(linea);
                    contenido.append("\n");
                }

                lector.close();

                // Mostrar el contenido en el editor
                txtEditor.setText(contenido.toString());

            } catch (IOException e) {

                JOptionPane.showMessageDialog(
                        this,
                        "No se pudo abrir el archivo.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
          JFileChooser selector = new JFileChooser();
          
            selector.setDialogTitle("Guardar archivo PromptZal");

            // Mostrar solamente archivos .pz
            FileNameExtensionFilter filtro =
                    new FileNameExtensionFilter(
                            "Archivos PromptZal (*.pz)",
                            "pz"
                    );

            selector.setFileFilter(filtro);

            int resultado = selector.showSaveDialog(this);

            if (resultado == JFileChooser.APPROVE_OPTION) {

                File archivo = selector.getSelectedFile();

                // Agregar .pz si el usuario no lo escribió
                String nombre = archivo.getName();

                if (!nombre.toLowerCase().endsWith(".pz")) {
                    archivo = new File(
                            archivo.getParentFile(),
                            nombre + ".pz"
                    );
                }

                try {

                    BufferedWriter escritor = new BufferedWriter(
                            new FileWriter(archivo)
                    );

                    escritor.write(txtEditor.getText());
                    escritor.close();

                    JOptionPane.showMessageDialog(
                            this,
                            "Archivo guardado correctamente como:\n"
                            + archivo.getName(),
                            "Guardar",
                            JOptionPane.INFORMATION_MESSAGE
                    );

                } catch (IOException e) {

                    JOptionPane.showMessageDialog(
                            this,
                            "No se pudo guardar el archivo.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        // TODO add your handling code here:
        
            // Obtener el código escrito en el editor
            String entrada = txtEditor.getText();

            // Crear el analizador léxico
            AnalizadorLexico analizador = new AnalizadorLexico(entrada);

            // Ejecutar el análisis
            analizador.analizar();

            // Obtener tokens y errores
            Token[] tokens = analizador.getTokens();
            ErrorLexico[] errores = analizador.getErrores();

            // Obtener los modelos de las tablas
            DefaultTableModel modeloTokens =
                    (DefaultTableModel) tablaTokens.getModel();

            DefaultTableModel modeloErrores =
                    (DefaultTableModel) tablaErrores.getModel();

            // Limpiar resultados anteriores
            modeloTokens.setRowCount(0);
            modeloErrores.setRowCount(0);

            // Mostrar tokens
            for (Token token : tokens) {

                modeloTokens.addRow(new Object[]{
                    token.getNumero(),
                    token.getLexema(),
                    token.getTipo(),
                    token.getFila(),
                    token.getColumna()
                });
            }

            // Mostrar errores
            for (ErrorLexico error : errores) {

                modeloErrores.addRow(new Object[]{
                    error.getLexema(),
                    error.getTipoError(),
                    error.getFila(),
                    error.getColumna()
                });
            }

            // Mostrar mensaje del resultado
            JOptionPane.showMessageDialog(
                    this,
                    "Análisis terminado.\n"
                    + "Tokens encontrados: " + tokens.length + "\n"
                    + "Errores encontrados: " + errores.length,
                    "Análisis léxico",
                    JOptionPane.INFORMATION_MESSAGE
            );
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void ReporteDeTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteDeTokensActionPerformed
        // TODO add your handling code here:
        
    // Obtener el código actual del editor
    String entrada = txtEditor.getText();

    // Crear el analizador léxico
    AnalizadorLexico analizador = new AnalizadorLexico(entrada);

    // Analizar el código
    analizador.analizar();

    // Obtener los tokens
    Token[] tokens = analizador.getTokens();

    // Crear objeto de reportes
    Reportes reportes = new Reportes();

    // Generar reporte HTML
    reportes.generarReporteTokens(tokens);

    // Avisar al usuario
    JOptionPane.showMessageDialog(
            this,
            "Reporte de tokens generado correctamente.\n"
            + "Archivo: reporte_tokens.html",
            "Reporte de Tokens",
            JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_ReporteDeTokensActionPerformed

    private void ReporteDeErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteDeErroresActionPerformed
        // TODO add your handling code here:
        String entrada = txtEditor.getText();

        AnalizadorLexico analizador = new AnalizadorLexico(entrada);
        analizador.analizar();

        ErrorLexico[] errores = analizador.getErrores();

        Reportes reportes = new Reportes();
        reportes.generarReporteErrores(errores);

        JOptionPane.showMessageDialog(
                this,
                "Reporte de errores generado correctamente.\n"
                + "Archivo: reporte_errores.html",
                "Reporte de Errores",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_ReporteDeErroresActionPerformed

    private void ReporteDeEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteDeEstadisticasActionPerformed
        String entrada = txtEditor.getText();

        AnalizadorLexico analizador = new AnalizadorLexico(entrada);
        analizador.analizar();

        Token[] tokens = analizador.getTokens();
        ErrorLexico[] errores = analizador.getErrores();

        Reportes reportes = new Reportes();
        reportes.generarReporteEstadisticas(tokens, errores);

        JOptionPane.showMessageDialog(
                this,
                "Reporte de estadísticas generado correctamente.\n"
                + "Archivo: reporte_estadisticas.html",
                "Reporte de Estadísticas",
                JOptionPane.INFORMATION_MESSAGE
        );

    }//GEN-LAST:event_ReporteDeEstadisticasActionPerformed

    private void GeneradorDeAFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneradorDeAFDActionPerformed
        // TODO add your handling code here:
        
        // Rutas de salida (ajusta la carpeta si quieres otra ubicación)
    String rutaDot = "salida/afd_promptzal.dot";
    String rutaImagen = "salida/afd_promptzal.png";

    GeneradorAFD.ResultadoRender resultado = GeneradorAFD.generarImagen(rutaDot, rutaImagen);

    if (resultado.exito) {
        // Mostrar la imagen en una ventana emergente
        javax.swing.ImageIcon icono = new javax.swing.ImageIcon(resultado.rutaImagen);
        javax.swing.JLabel label = new javax.swing.JLabel(icono);
        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(label);
        scroll.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.JDialog dialogo = new javax.swing.JDialog(this, "AFD de PromptZal", true);
        dialogo.getContentPane().add(scroll);
        dialogo.pack();
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
                resultado.mensajeError,
                "Error al generar el AFD",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_GeneradorDeAFDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem GeneradorDeAFD;
    private javax.swing.JMenuItem ReporteDeErrores;
    private javax.swing.JMenuItem ReporteDeEstadisticas;
    private javax.swing.JMenuItem ReporteDeTokens;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaErrores;
    private javax.swing.JTable tablaTokens;
    private javax.swing.JTextArea txtEditor;
    // End of variables declaration//GEN-END:variables
}
