/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Analizador.AnalizadorLexico;
import graficos.GeneradorAFD;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelos.ErrorLexico;
import modelos.Reportes;
import modelos.Token;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;

/**
 *
 * @author fernan
 */
public class Vista extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista.class.getName());
    private File archivoActual = null;

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        configurarTablaTokens();
        configurarTablaErrores();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEditor = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTokens = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaErrores = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAnalizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        MenuNuevo = new javax.swing.JMenuItem();
        MenuAbrir = new javax.swing.JMenuItem();
        MenuGuardar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ReporteDeTokens = new javax.swing.JMenuItem();
        ReporteDeErrores = new javax.swing.JMenuItem();
        ReporteDeEstadisticas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        GeneradorDeAFD = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PromptZal - Analizador Lexico");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEditor.setColumns(20);
        txtEditor.setRows(5);
        txtEditor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(txtEditor);

        panelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 70, 1408, 253));

        jLabel1.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo PromptZal");
        panelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 34, -1, -1));

        jScrollPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tablaTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Lexema", "Tipo", "Linea", "Columna"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaTokens);

        panelPrincipal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 448, 684, 254));

        jScrollPane3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tablaErrores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Lexema", "Tipo de Error", "Fila", "Columna"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaErrores);

        panelPrincipal.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(906, 448, 633, 254));

        jLabel2.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tokens");
        panelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 412, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Errores");
        panelPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 410, -1, -1));

        btnAnalizar.setBackground(new java.awt.Color(255, 204, 51));
        btnAnalizar.setForeground(new java.awt.Color(0, 0, 0));
        btnAnalizar.setText("Analizar");
        btnAnalizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnAnalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 780, 140, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura desde 2026-09-04 23-17-40.png"))); // NOI18N
        panelPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 1680, 990));

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1580, 1000));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen pegada.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 30, 310, 950));

        jMenu3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu3.setText("Archivo");

        MenuNuevo.setText("Nuevo");
        MenuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNuevoActionPerformed(evt);
            }
        });
        jMenu3.add(MenuNuevo);

        MenuAbrir.setText("Abrir");
        MenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAbrirActionPerformed(evt);
            }
        });
        jMenu3.add(MenuAbrir);

        MenuGuardar.setText("Guardar");
        MenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGuardarActionPerformed(evt);
            }
        });
        jMenu3.add(MenuGuardar);

        jMenuBar1.add(jMenu3);

        jMenu5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu5.setText("Reportes");

        ReporteDeTokens.setText("Reporte de Tokens");
        ReporteDeTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteDeTokensActionPerformed(evt);
            }
        });
        jMenu5.add(ReporteDeTokens);

        ReporteDeErrores.setText("Reporte de Errores");
        ReporteDeErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteDeErroresActionPerformed(evt);
            }
        });
        jMenu5.add(ReporteDeErrores);

        ReporteDeEstadisticas.setText("Estadisticas");
        ReporteDeEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteDeEstadisticasActionPerformed(evt);
            }
        });
        jMenu5.add(ReporteDeEstadisticas);

        jMenuBar1.add(jMenu5);

        jMenu6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu6.setText("Automata");

        GeneradorDeAFD.setText("Generar AFD");
        GeneradorDeAFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneradorDeAFDActionPerformed(evt);
            }
        });
        jMenu6.add(GeneradorDeAFD);

        jMenuBar1.add(jMenu6);

        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("Salir");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNuevoActionPerformed
        // TODO add your handling code here:
        txtEditor.setText("");
        DefaultTableModel modeloTokens
                = (DefaultTableModel) tablaTokens.getModel();
        modeloTokens.setRowCount(0);
        DefaultTableModel modeloErrores
                = (DefaultTableModel) tablaErrores.getModel();
        modeloErrores.setRowCount(0);
        // Quitar resaltados del editor
        txtEditor.getHighlighter().removeAllHighlights();
        // Ya no hay archivo asociado
        archivoActual = null;
    }//GEN-LAST:event_MenuNuevoActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        // Obtener el código escrito en el editor
        String entrada = txtEditor.getText();

        // Crear el analizador léxico
        AnalizadorLexico analizador = new AnalizadorLexico(entrada);

        // Ejecutar el análisis
        analizador.analizar();

        // Obtener tokens y errores
        Token[] tokens = analizador.getTokens();
        ErrorLexico[] errores = analizador.getErrores();

        // Obtener los modelos de las tablas
        DefaultTableModel modeloTokens
                = (DefaultTableModel) tablaTokens.getModel();

        DefaultTableModel modeloErrores
                = (DefaultTableModel) tablaErrores.getModel();

        // Limpiar resultados anteriores
        modeloTokens.setRowCount(0);
        modeloErrores.setRowCount(0);

        // Quitar resaltados anteriores del editor
        txtEditor.getHighlighter().removeAllHighlights();

        // Mostrar tokens
        for (Token token : tokens) {

            modeloTokens.addRow(new Object[]{
                token.getNumero(),
                token.getLexema(),
                token.getTipo(),
                token.getFila(),
                token.getColumna()
            });
        }

        // Mostrar errores
        for (ErrorLexico error : errores) {

            modeloErrores.addRow(new Object[]{
                error.getLexema(),
                error.getTipoError(),
                error.getFila(),
                error.getColumna()
            });
        }
        marcarLineasConErrores(errores);

        // Mostrar mensaje del resultado
        JOptionPane.showMessageDialog(
                this,
                "Análisis terminado.\n"
                + "Tokens encontrados: " + tokens.length + "\n"
                + "Errores encontrados: " + errores.length,
                "Análisis léxico",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void ReporteDeTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteDeTokensActionPerformed
        // TODO add your handling code here:
        String entrada = txtEditor.getText();

        AnalizadorLexico analizador = new AnalizadorLexico(entrada);
        analizador.analizar();

        Token[] tokens = analizador.getTokens();

        JFileChooser selector = new JFileChooser();

        selector.setDialogTitle("Guardar reporte de tokens");

        selector.setSelectedFile(
                new File("reporte_tokens.html")
        );

        int resultado = selector.showSaveDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {

            File archivo = selector.getSelectedFile();

            String ruta = archivo.getAbsolutePath();

            if (!ruta.toLowerCase().endsWith(".html")) {
                ruta = ruta + ".html";
            }

            Reportes reportes = new Reportes();

            reportes.generarReporteTokens(
                    tokens,
                    ruta
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Reporte de tokens generado correctamente.\n"
                    + "Archivo: " + ruta,
                    "Reporte de Tokens",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_ReporteDeTokensActionPerformed

    private void ReporteDeErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteDeErroresActionPerformed
        // TODO add your handling code here:
        
        String entrada = txtEditor.getText();

        AnalizadorLexico analizador = new AnalizadorLexico(entrada);
        analizador.analizar();

        ErrorLexico[] errores = analizador.getErrores();

        JFileChooser selector = new JFileChooser();

        selector.setDialogTitle("Guardar reporte de errores");

        selector.setSelectedFile(
                new File("reporte_errores.html")
        );

        int resultado = selector.showSaveDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {

            File archivo = selector.getSelectedFile();

            String ruta = archivo.getAbsolutePath();

            if (!ruta.toLowerCase().endsWith(".html")) {
                ruta = ruta + ".html";
            }

            Reportes reportes = new Reportes();

            reportes.generarReporteErrores(
                    errores,
                    ruta
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Reporte de errores generado correctamente.\n"
                    + "Archivo: " + ruta,
                    "Reporte de Errores",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_ReporteDeErroresActionPerformed

    private void ReporteDeEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteDeEstadisticasActionPerformed
        
        String entrada = txtEditor.getText();

        AnalizadorLexico analizador = new AnalizadorLexico(entrada);
        analizador.analizar();

        Token[] tokens = analizador.getTokens();
        ErrorLexico[] errores = analizador.getErrores();

        JFileChooser selector = new JFileChooser();

        selector.setDialogTitle("Guardar reporte de estadísticas");

        selector.setSelectedFile(
                new File("reporte_estadisticas.html")
        );

        int resultado = selector.showSaveDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {

            File archivo = selector.getSelectedFile();

            String ruta = archivo.getAbsolutePath();

            if (!ruta.toLowerCase().endsWith(".html")) {
                ruta = ruta + ".html";
            }

            Reportes reportes = new Reportes();

            reportes.generarReporteEstadisticas(
                    tokens,
                    errores,
                    analizador.getFilaActual(),
                    ruta
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Reporte de estadísticas generado correctamente.\n"
                    + "Archivo: " + ruta,
                    "Reporte de Estadísticas",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_ReporteDeEstadisticasActionPerformed

    private void GeneradorDeAFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneradorDeAFDActionPerformed
        // TODO add your handling code here: 
        String rutaDot = "salida/afd_promptzal.dot";
        String rutaImagen = "salida/afd_promptzal.png";

        GeneradorAFD.ResultadoRender resultado =
                GeneradorAFD.generarImagen(rutaDot, rutaImagen);

        if (resultado.exito) {

            javax.swing.ImageIcon icono =
                    new javax.swing.ImageIcon(resultado.rutaImagen);

            javax.swing.JLabel label =
                    new javax.swing.JLabel(icono);

            javax.swing.JScrollPane scroll =
                    new javax.swing.JScrollPane(label);

            scroll.setPreferredSize(
                    new java.awt.Dimension(800, 600)
            );

            javax.swing.JDialog dialogo =
                    new javax.swing.JDialog(this, "AFD de PromptZal", true);

            dialogo.getContentPane().add(scroll);

            dialogo.pack();
            dialogo.setLocationRelativeTo(this);
            dialogo.setVisible(true);

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    resultado.mensajeError,
                    "Error al generar el AFD",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_GeneradorDeAFDActionPerformed

    private void MenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGuardarActionPerformed
        // TODO add your handling code here:

        if (archivoActual == null) {

            JFileChooser selector = new JFileChooser();
            selector.setDialogTitle("Guardar archivo PromptZal");

            FileNameExtensionFilter filtro
                    = new FileNameExtensionFilter(
                            "Archivos PromptZal (*.pz)",
                            "pz"
                    );

            selector.setFileFilter(filtro);

            int resultado = selector.showSaveDialog(this);

            if (resultado != JFileChooser.APPROVE_OPTION) {
                return;
            }

            archivoActual = selector.getSelectedFile();

            String nombre = archivoActual.getName();

            if (!nombre.toLowerCase().endsWith(".pz")) {

                archivoActual = new File(
                        archivoActual.getParentFile(),
                        nombre + ".pz"
                );
            }
        }

        try {

            BufferedWriter escritor
                    = new BufferedWriter(
                            new FileWriter(archivoActual)
                    );

            escritor.write(txtEditor.getText());

            escritor.close();

            JOptionPane.showMessageDialog(
                    this,
                    "Archivo guardado correctamente:\n"
                    + archivoActual.getName(),
                    "Guardar",
                    JOptionPane.INFORMATION_MESSAGE
            );

        } catch (IOException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo guardar el archivo.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_MenuGuardarActionPerformed

    private void MenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAbrirActionPerformed

        JFileChooser selector = new JFileChooser();
        selector.setDialogTitle("Abrir archivo PromptZal");

        FileNameExtensionFilter filtro
                = new FileNameExtensionFilter(
                        "Archivos PromptZal (*.pz)",
                        "pz"
                );

        selector.setFileFilter(filtro);

        int resultado = selector.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {

            File archivo = selector.getSelectedFile();

            try {

                BufferedReader lector
                        = new BufferedReader(new FileReader(archivo));

                StringBuilder contenido = new StringBuilder();

                String linea;

                while ((linea = lector.readLine()) != null) {
                    contenido.append(linea);
                    contenido.append("\n");
                }

                lector.close();

                txtEditor.setText(contenido.toString());
                DefaultTableModel modeloTokens =
                        (DefaultTableModel) tablaTokens.getModel();
                modeloTokens.setRowCount(0);
                DefaultTableModel modeloErrores =
                        (DefaultTableModel) tablaErrores.getModel();
                modeloErrores.setRowCount(0);
                txtEditor.getHighlighter().removeAllHighlights();

                // Guardamos el archivo que está abierto
                archivoActual = archivo;

                JOptionPane.showMessageDialog(
                        this,
                        "Archivo abierto correctamente.",
                        "Abrir",
                        JOptionPane.INFORMATION_MESSAGE
                );

            } catch (IOException e) {

                JOptionPane.showMessageDialog(
                        this,
                        "No se pudo abrir el archivo.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_MenuAbrirActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem GeneradorDeAFD;
    private javax.swing.JMenuItem MenuAbrir;
    private javax.swing.JMenuItem MenuGuardar;
    private javax.swing.JMenuItem MenuNuevo;
    private javax.swing.JMenuItem ReporteDeErrores;
    private javax.swing.JMenuItem ReporteDeEstadisticas;
    private javax.swing.JMenuItem ReporteDeTokens;
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaErrores;
    private javax.swing.JTable tablaTokens;
    private javax.swing.JTextArea txtEditor;
    // End of variables declaration//GEN-END:variables
   private void configurarTablaTokens() {

        tablaTokens.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(
                    JTable table,
                    Object value,
                    boolean isSelected,
                    boolean hasFocus,
                    int row,
                    int column) {

                Component componente
                        = super.getTableCellRendererComponent(
                                table,
                                value,
                                isSelected,
                                hasFocus,
                                row,
                                column
                        );

                if (!isSelected) {
                    componente.setBackground(new Color(220, 255, 220));
                    componente.setForeground(Color.BLACK);
                }

                return componente;
            }
        });
    }

    private void configurarTablaErrores() {

        tablaErrores.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(
                    JTable table,
                    Object value,
                    boolean isSelected,
                    boolean hasFocus,
                    int row,
                    int column) {

                Component componente
                        = super.getTableCellRendererComponent(
                                table,
                                value,
                                isSelected,
                                hasFocus,
                                row,
                                column
                        );

                if (!isSelected) {
                    componente.setBackground(new Color(255, 220, 220));
                    componente.setForeground(Color.BLACK);
                }

                return componente;
            }
        });
    }

    private void marcarLineasConErrores(ErrorLexico[] errores) {

        Highlighter highlighter = txtEditor.getHighlighter();

        // Quitar resaltados anteriores
        highlighter.removeAllHighlights();

        // Recorrer todos los errores
        for (ErrorLexico error : errores) {

            try {

                int linea = error.getFila() - 1;

                int inicio = txtEditor.getLineStartOffset(linea);
                int fin = txtEditor.getLineEndOffset(linea);

                highlighter.addHighlight(
                        inicio,
                        fin,
                        new DefaultHighlighter.DefaultHighlightPainter(
                                new Color(255, 220, 220)
                        )
                );

            } catch (Exception e) {

                System.out.println(
                        "No se pudo marcar la línea "
                        + error.getFila()
                );
            }
        }
    }
}
